// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

import { Writer, Reader } from 'as-proto/assembly';

export class JitInherentRequest {
  static encode(message: JitInherentRequest, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.sender);

    writer.uint32(18);
    writer.bytes(message.nonce);

    writer.uint32(26);
    writer.bytes(message.initCode);

    writer.uint32(34);
    writer.bytes(message.callData);

    writer.uint32(42);
    writer.bytes(message.callGasLimit);

    writer.uint32(50);
    writer.bytes(message.verificationGasLimit);

    writer.uint32(58);
    writer.bytes(message.maxFeePerGas);

    writer.uint32(66);
    writer.bytes(message.maxPriorityFeePerGas);

    writer.uint32(74);
    writer.bytes(message.paymasterAndData);
  }

  static decode(reader: Reader, length: i32): JitInherentRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new JitInherentRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.bytes();
          break;

        case 2:
          message.nonce = reader.bytes();
          break;

        case 3:
          message.initCode = reader.bytes();
          break;

        case 4:
          message.callData = reader.bytes();
          break;

        case 5:
          message.callGasLimit = reader.bytes();
          break;

        case 6:
          message.verificationGasLimit = reader.bytes();
          break;

        case 7:
          message.maxFeePerGas = reader.bytes();
          break;

        case 8:
          message.maxPriorityFeePerGas = reader.bytes();
          break;

        case 9:
          message.paymasterAndData = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: Uint8Array;
  nonce: Uint8Array;
  initCode: Uint8Array;
  callData: Uint8Array;
  callGasLimit: Uint8Array;
  verificationGasLimit: Uint8Array;
  maxFeePerGas: Uint8Array;
  maxPriorityFeePerGas: Uint8Array;
  paymasterAndData: Uint8Array;

  constructor(
    sender: Uint8Array = new Uint8Array(0),
    nonce: Uint8Array = new Uint8Array(0),
    initCode: Uint8Array = new Uint8Array(0),
    callData: Uint8Array = new Uint8Array(0),
    callGasLimit: Uint8Array = new Uint8Array(0),
    verificationGasLimit: Uint8Array = new Uint8Array(0),
    maxFeePerGas: Uint8Array = new Uint8Array(0),
    maxPriorityFeePerGas: Uint8Array = new Uint8Array(0),
    paymasterAndData: Uint8Array = new Uint8Array(0),
  ) {
    this.sender = sender;
    this.nonce = nonce;
    this.initCode = initCode;
    this.callData = callData;
    this.callGasLimit = callGasLimit;
    this.verificationGasLimit = verificationGasLimit;
    this.maxFeePerGas = maxFeePerGas;
    this.maxPriorityFeePerGas = maxPriorityFeePerGas;
    this.paymasterAndData = paymasterAndData;
  }
}
