// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader } from "as-proto/assembly";
import { InnerTransaction } from "./inner-transaction";

export class InnerTransactions {
  static encode(message: InnerTransactions, writer: Writer): void {
    const txs = message.txs;
    for (let i: i32 = 0; i < txs.length; ++i) {
      writer.uint32(10);
      writer.fork();
      InnerTransaction.encode(txs[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): InnerTransactions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InnerTransactions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.txs.push(InnerTransaction.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  txs: Array<InnerTransaction>;

  constructor(txs: Array<InnerTransaction> = []) {
    this.txs = txs;
  }
}
