// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader } from "as-proto/assembly";

export class InnerTransaction {
  static encode(message: InnerTransaction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.from);

    writer.uint32(18);
    writer.string(message.to);

    writer.uint32(26);
    writer.bytes(message.data);

    writer.uint32(34);
    writer.string(message.value);

    writer.uint32(42);
    writer.string(message.gas);

    writer.uint32(48);
    writer.uint64(message.index);

    const parent = message.parent;
    if (parent !== null) {
      writer.uint32(58);
      writer.fork();
      InnerTransaction.encode(parent, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): InnerTransaction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InnerTransaction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.from = reader.string();
          break;

        case 2:
          message.to = reader.string();
          break;

        case 3:
          message.data = reader.bytes();
          break;

        case 4:
          message.value = reader.string();
          break;

        case 5:
          message.gas = reader.string();
          break;

        case 6:
          message.index = reader.uint64();
          break;

        case 7:
          message.parent = InnerTransaction.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  from: string;
  to: string;
  data: Uint8Array;
  value: string;
  gas: string;
  index: u64;
  parent: InnerTransaction | null;

  constructor(
    from: string = "",
    to: string = "",
    data: Uint8Array = new Uint8Array(0),
    value: string = "",
    gas: string = "",
    index: u64 = 0,
    parent: InnerTransaction | null = null
  ) {
    this.from = from;
    this.to = to;
    this.data = data;
    this.value = value;
    this.gas = gas;
    this.index = index;
    this.parent = parent;
  }
}
