// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader } from "as-proto/assembly";

export class StateChange {
  static encode(message: StateChange, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.account);

    writer.uint32(18);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): StateChange {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StateChange();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;
  value: Uint8Array;

  constructor(account: string = "", value: Uint8Array = new Uint8Array(0)) {
    this.account = account;
    this.value = value;
  }
}
