// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

export enum ValueKind {
  INT16 = 0,
  INT32 = 1,
  INT64 = 2,
  INT256 = 3,
  UINT16 = 4,
  UINT32 = 5,
  UINT64 = 6,
  UINT256 = 7,
  BOOL = 8,
  STRING = 9,
}
