// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

import { Writer, Reader } from 'as-proto/assembly';

export class Any {
  static encode(message: Any, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.typeUrl);

    writer.uint32(18);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): Any {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Any();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.typeUrl = reader.string();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  typeUrl: string;
  value: Uint8Array;

  constructor(typeUrl: string = '', value: Uint8Array = new Uint8Array(0)) {
    this.typeUrl = typeUrl;
    this.value = value;
  }
}
