// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

import { Writer, Reader } from 'as-proto/assembly';

export class ScheduleId {
  static encode(message: ScheduleId, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.scheduleName);

    writer.uint32(18);
    writer.string(message.aspectId);
  }

  static decode(reader: Reader, length: i32): ScheduleId {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ScheduleId();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.scheduleName = reader.string();
          break;

        case 2:
          message.aspectId = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  scheduleName: string;
  aspectId: string;

  constructor(scheduleName: string = '', aspectId: string = '') {
    this.scheduleName = scheduleName;
    this.aspectId = aspectId;
  }
}
