// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from "as-proto/assembly";

export class AddressQueryRequest {
  static encode(message: AddressQueryRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.addressEquals);
  }

  static decode(reader: Reader, length: i32): AddressQueryRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AddressQueryRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.addressEquals = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  addressEquals: string;

  constructor(addressEquals: string = "") {
    this.addressEquals = addressEquals;
  }
}
