// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.27.1

import { Writer, Reader } from "as-proto/assembly";
import { G1 } from "./g1";

export class Bn256ScalarMulInput {
  static encode(message: Bn256ScalarMulInput, writer: Writer): void {
    const a = message.a;
    if (a !== null) {
      writer.uint32(10);
      writer.fork();
      G1.encode(a, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.bytes(message.scalar);
  }

  static decode(reader: Reader, length: i32): Bn256ScalarMulInput {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Bn256ScalarMulInput();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.a = G1.decode(reader, reader.uint32());
          break;

        case 2:
          message.scalar = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  a: G1 | null;
  scalar: Uint8Array;

  constructor(a: G1 | null = null, scalar: Uint8Array = new Uint8Array(0)) {
    this.a = a;
    this.scalar = scalar;
  }
}
