// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Writer, Reader } from 'as-proto/assembly';
import { EthMessage } from './eth-message';

export class CallMessageRequest {
  static encode(message: CallMessageRequest, writer: Writer): void {
    const message_2 = message.message;
    if (message_2 !== null) {
      writer.uint32(10);
      writer.fork();
      EthMessage.encode(message_2, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CallMessageRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CallMessageRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.message = EthMessage.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  message: EthMessage | null;

  constructor(message: EthMessage | null = null) {
    this.message = message;
  }
}
