// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from "as-proto/assembly";
import { BlockParams } from "./block-params";
import { Evidence } from "./evidence";
import { Validator } from "./validator";
import { Version } from "./version";

export class ConsParams {
  static encode(message: ConsParams, writer: Writer): void {
    const block = message.block;
    if (block !== null) {
      writer.uint32(10);
      writer.fork();
      BlockParams.encode(block, writer);
      writer.ldelim();
    }

    const evidence = message.evidence;
    if (evidence !== null) {
      writer.uint32(18);
      writer.fork();
      Evidence.encode(evidence, writer);
      writer.ldelim();
    }

    const validator = message.validator;
    if (validator !== null) {
      writer.uint32(26);
      writer.fork();
      Validator.encode(validator, writer);
      writer.ldelim();
    }

    const version = message.version;
    if (version !== null) {
      writer.uint32(34);
      writer.fork();
      Version.encode(version, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ConsParams {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ConsParams();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.block = BlockParams.decode(reader, reader.uint32());
          break;

        case 2:
          message.evidence = Evidence.decode(reader, reader.uint32());
          break;

        case 3:
          message.validator = Validator.decode(reader, reader.uint32());
          break;

        case 4:
          message.version = Version.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  block: BlockParams | null;
  evidence: Evidence | null;
  validator: Validator | null;
  version: Version | null;

  constructor(
    block: BlockParams | null = null,
    evidence: Evidence | null = null,
    validator: Validator | null = null,
    version: Version | null = null
  ) {
    this.block = block;
    this.evidence = evidence;
    this.validator = validator;
    this.version = version;
  }
}
