// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

import { Writer, Reader } from 'as-proto/assembly';
import { SetNameSpace } from './set-name-space';

export class ContextSetRequest {
  static encode(message: ContextSetRequest, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.nameSpace);

    writer.uint32(18);
    writer.string(message.key);

    writer.uint32(26);
    writer.string(message.value);
  }

  static decode(reader: Reader, length: i32): ContextSetRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ContextSetRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.nameSpace = reader.int32();
          break;

        case 2:
          message.key = reader.string();
          break;

        case 3:
          message.value = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  nameSpace: SetNameSpace;
  key: string;
  value: string;

  constructor(nameSpace: SetNameSpace = 0, key: string = '', value: string = '') {
    this.nameSpace = nameSpace;
    this.key = key;
    this.value = value;
  }
}
