// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

export enum DataSpaceType {
  TX_ASPECT_CONTEXT = 0,
  TX_EXT_PROPERTIES = 1,
  TX_CONTENT = 2,
  TX_STATE_CHANGES = 3,
  TX_CALL_TREE = 4,
  TX_RECEIPT = 5,
  TX_GAS_METER = 6,
  ENV_CONS_PARAMS = 7,
  ENV_CHAIN_CONFIG = 8,
  ENV_EVM_PARAMS = 9,
  ENV_BASE_INFO = 10,
  BLOCK_HEADER = 11,
  BLOCK_TXS = 12,
  BLOCK_GAS_METER = 13,
  BLOCK_MIN_GAS_PRICE = 14,
  BLOCK_LAST_COMMIT = 15,
  BLOCK_BLOCK_ID = 16,
  BLOCK_EVIDENCE = 17,
}
