// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

import { Writer, Reader } from 'as-proto/assembly';

export class EthStateChange {
  static encode(message: EthStateChange, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.account);

    writer.uint32(18);
    writer.bytes(message.value);

    writer.uint32(24);
    writer.uint64(message.callIndex);
  }

  static decode(reader: Reader, length: i32): EthStateChange {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EthStateChange();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        case 3:
          message.callIndex = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;
  value: Uint8Array;
  callIndex: u64;

  constructor(account: string = '', value: Uint8Array = new Uint8Array(0), callIndex: u64 = 0) {
    this.account = account;
    this.value = value;
    this.callIndex = callIndex;
  }
}
