// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Writer, Reader } from 'as-proto/assembly';
import { EthAccessTuple } from './eth-access-tuple';

export class EthTransaction {
  static encode(message: EthTransaction, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.blockHash);

    writer.uint32(16);
    writer.int64(message.blockNumber);

    writer.uint32(26);
    writer.string(message.from);

    writer.uint32(32);
    writer.uint64(message.gas);

    writer.uint32(42);
    writer.string(message.gasPrice);

    writer.uint32(50);
    writer.string(message.gasFeeCap);

    writer.uint32(58);
    writer.string(message.gasTipCap);

    writer.uint32(66);
    writer.bytes(message.hash);

    writer.uint32(74);
    writer.bytes(message.input);

    writer.uint32(80);
    writer.uint64(message.nonce);

    writer.uint32(90);
    writer.string(message.to);

    writer.uint32(96);
    writer.int64(message.transactionIndex);

    writer.uint32(106);
    writer.string(message.value);

    writer.uint32(112);
    writer.int32(message.type);

    const accessList = message.accessList;
    for (let i: i32 = 0; i < accessList.length; ++i) {
      writer.uint32(122);
      writer.fork();
      EthAccessTuple.encode(accessList[i], writer);
      writer.ldelim();
    }

    writer.uint32(130);
    writer.string(message.chainId);

    writer.uint32(138);
    writer.bytes(message.v);

    writer.uint32(146);
    writer.bytes(message.r);

    writer.uint32(154);
    writer.bytes(message.s);
  }

  static decode(reader: Reader, length: i32): EthTransaction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EthTransaction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.blockHash = reader.bytes();
          break;

        case 2:
          message.blockNumber = reader.int64();
          break;

        case 3:
          message.from = reader.string();
          break;

        case 4:
          message.gas = reader.uint64();
          break;

        case 5:
          message.gasPrice = reader.string();
          break;

        case 6:
          message.gasFeeCap = reader.string();
          break;

        case 7:
          message.gasTipCap = reader.string();
          break;

        case 8:
          message.hash = reader.bytes();
          break;

        case 9:
          message.input = reader.bytes();
          break;

        case 10:
          message.nonce = reader.uint64();
          break;

        case 11:
          message.to = reader.string();
          break;

        case 12:
          message.transactionIndex = reader.int64();
          break;

        case 13:
          message.value = reader.string();
          break;

        case 14:
          message.type = reader.int32();
          break;

        case 15:
          message.accessList.push(EthAccessTuple.decode(reader, reader.uint32()));
          break;

        case 16:
          message.chainId = reader.string();
          break;

        case 17:
          message.v = reader.bytes();
          break;

        case 18:
          message.r = reader.bytes();
          break;

        case 19:
          message.s = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  blockHash: Uint8Array;
  blockNumber: i64;
  from: string;
  gas: u64;
  gasPrice: string;
  gasFeeCap: string;
  gasTipCap: string;
  hash: Uint8Array;
  input: Uint8Array;
  nonce: u64;
  to: string;
  transactionIndex: i64;
  value: string;
  type: i32;
  accessList: Array<EthAccessTuple>;
  chainId: string;
  v: Uint8Array;
  r: Uint8Array;
  s: Uint8Array;

  constructor(
    blockHash: Uint8Array = new Uint8Array(0),
    blockNumber: i64 = 0,
    from: string = '',
    gas: u64 = 0,
    gasPrice: string = '',
    gasFeeCap: string = '',
    gasTipCap: string = '',
    hash: Uint8Array = new Uint8Array(0),
    input: Uint8Array = new Uint8Array(0),
    nonce: u64 = 0,
    to: string = '',
    transactionIndex: i64 = 0,
    value: string = '',
    type: i32 = 0,
    accessList: Array<EthAccessTuple> = [],
    chainId: string = '',
    v: Uint8Array = new Uint8Array(0),
    r: Uint8Array = new Uint8Array(0),
    s: Uint8Array = new Uint8Array(0),
  ) {
    this.blockHash = blockHash;
    this.blockNumber = blockNumber;
    this.from = from;
    this.gas = gas;
    this.gasPrice = gasPrice;
    this.gasFeeCap = gasFeeCap;
    this.gasTipCap = gasTipCap;
    this.hash = hash;
    this.input = input;
    this.nonce = nonce;
    this.to = to;
    this.transactionIndex = transactionIndex;
    this.value = value;
    this.type = type;
    this.accessList = accessList;
    this.chainId = chainId;
    this.v = v;
    this.r = r;
    this.s = s;
  }
}
