// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Writer, Reader } from 'as-proto/assembly';

export class EthTxQuery {
  static encode(message: EthTxQuery, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.gasLimitGt);
  }

  static decode(reader: Reader, length: i32): EthTxQuery {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EthTxQuery();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.gasLimitGt = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  gasLimitGt: u64;

  constructor(gasLimitGt: u64 = 0) {
    this.gasLimitGt = gasLimitGt;
  }
}
