// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from 'as-proto/assembly';

export class EthInnerTransaction {
  static encode(message: EthInnerTransaction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.from);

    writer.uint32(18);
    writer.string(message.to);

    writer.uint32(26);
    writer.bytes(message.data);

    writer.uint32(34);
    writer.string(message.value);

    writer.uint32(42);
    writer.string(message.gas);
  }

  static decode(reader: Reader, length: i32): EthInnerTransaction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EthInnerTransaction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.from = reader.string();
          break;

        case 2:
          message.to = reader.string();
          break;

        case 3:
          message.data = reader.bytes();
          break;

        case 4:
          message.value = reader.string();
          break;

        case 5:
          message.gas = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  from: string;
  to: string;
  data: Uint8Array;
  value: string;
  gas: string;

  constructor(
    from: string = '',
    to: string = '',
    data: Uint8Array = new Uint8Array(0),
    value: string = '',
    gas: string = '',
  ) {
    this.from = from;
    this.to = to;
    this.data = data;
    this.value = value;
    this.gas = gas;
  }
}
