// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from 'as-proto/assembly';

export class EthStateChangeIndices {
  static encode(message: EthStateChangeIndices, writer: Writer): void {
    const indices = message.indices;
    if (indices.length !== 0) {
      for (let i: i32 = 0; i < indices.length; ++i) {
        writer.uint32(10);
        writer.bytes(indices[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): EthStateChangeIndices {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EthStateChangeIndices();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.indices.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  indices: Array<Uint8Array>;

  constructor(indices: Array<Uint8Array> = []) {
    this.indices = indices;
  }
}
