// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Protobuf, Reader, Writer } from "as-proto/assembly";

export class EthStateChange {
  static encode(message: EthStateChange, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.account);

    writer.uint32(18);
    writer.bytes(message.value);

    writer.uint32(24);
    writer.uint64(message.callIndex);
  }

  static decode(reader: Reader, length: i32): EthStateChange {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EthStateChange();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.bytes();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        case 3:
          message.callIndex = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: Uint8Array;
  value: Uint8Array;
  callIndex: u64;

  constructor(
    account: Uint8Array = new Uint8Array(0),
    value: Uint8Array = new Uint8Array(0),
    callIndex: u64 = 0
  ) {
    this.account = account;
    this.value = value;
    this.callIndex = callIndex;
  }
}

export function encodeEthStateChange(message: EthStateChange): Uint8Array {
  return Protobuf.encode(message, EthStateChange.encode);
}

export function decodeEthStateChange(buffer: Uint8Array): EthStateChange {
  return Protobuf.decode<EthStateChange>(buffer, EthStateChange.decode);
}
