// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from "as-proto/assembly";

export class IntData {
  static encode(message: IntData, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.data);
  }

  static decode(reader: Reader, length: i32): IntData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new IntData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.data = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  data: i64;

  constructor(data: i64 = 0) {
    this.data = data;
  }
}
