// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Protobuf, Reader, Writer } from 'as-proto/assembly';

export class NoFromTxInput {
  static encode(message: NoFromTxInput, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.hash);

    writer.uint32(18);
    writer.bytes(message.to);
  }

  static decode(reader: Reader, length: i32): NoFromTxInput {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NoFromTxInput();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.hash = reader.bytes();
          break;

        case 2:
          message.to = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  hash: Uint8Array;
  to: Uint8Array;

  constructor(hash: Uint8Array = new Uint8Array(0), to: Uint8Array = new Uint8Array(0)) {
    this.hash = hash;
    this.to = to;
  }
}

export function encodeNoFromTxInput(message: NoFromTxInput): Uint8Array {
  return Protobuf.encode(message, NoFromTxInput.encode);
}

export function decodeNoFromTxInput(buffer: Uint8Array): NoFromTxInput {
  return Protobuf.decode<NoFromTxInput>(buffer, NoFromTxInput.decode);
}
