// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from 'as-proto/assembly';

export class PartSetHeader {
  static encode(message: PartSetHeader, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.total);

    writer.uint32(18);
    writer.bytes(message.hash);
  }

  static decode(reader: Reader, length: i32): PartSetHeader {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PartSetHeader();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.total = reader.uint32();
          break;

        case 2:
          message.hash = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  total: u32;
  hash: Uint8Array;

  constructor(total: u32 = 0, hash: Uint8Array = new Uint8Array(0)) {
    this.total = total;
    this.hash = hash;
  }
}
