// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Writer, Reader } from 'as-proto/assembly';

export class ReceiptInput {
  static encode(message: ReceiptInput, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.status);
  }

  static decode(reader: Reader, length: i32): ReceiptInput {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ReceiptInput();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.status = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  status: u64;

  constructor(status: u64 = 0) {
    this.status = status;
  }
}
