// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

export enum RemoveNameSpace {
  RemoveAspectContext = 0,
  RemoveAspectState = 1,
}
