// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from "as-proto/assembly";

export class StateLogQueryRequest {
  static encode(message: StateLogQueryRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.topicEquals);

    writer.uint32(18);
    writer.string(message.addressEquals);

    writer.uint32(26);
    writer.string(message.txHashEquals);
  }

  static decode(reader: Reader, length: i32): StateLogQueryRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StateLogQueryRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.topicEquals = reader.string();
          break;

        case 2:
          message.addressEquals = reader.string();
          break;

        case 3:
          message.txHashEquals = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  topicEquals: string;
  addressEquals: string;
  txHashEquals: string;

  constructor(
    topicEquals: string = "",
    addressEquals: string = "",
    txHashEquals: string = ""
  ) {
    this.topicEquals = topicEquals;
    this.addressEquals = addressEquals;
    this.txHashEquals = txHashEquals;
  }
}
