// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.3

import { Writer, Reader } from 'as-proto/assembly';

export class StringData {
  static encode(message: StringData, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.data);
  }

  static decode(reader: Reader, length: i32): StringData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StringData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.data = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  data: string;

  constructor(data: string = '') {
    this.data = data;
  }
}
