// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from "as-proto/assembly";
import { RunResult } from "./run-result";

export class StringDataResponse {
  static encode(message: StringDataResponse, writer: Writer): void {
    const result = message.result;
    if (result !== null) {
      writer.uint32(10);
      writer.fork();
      RunResult.encode(result, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.data);
  }

  static decode(reader: Reader, length: i32): StringDataResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StringDataResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.result = RunResult.decode(reader, reader.uint32());
          break;

        case 2:
          message.data = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  result: RunResult | null;
  data: string;

  constructor(result: RunResult | null = null, data: string = "") {
    this.result = result;
    this.data = data;
  }
}
