// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Protobuf, Reader, Writer } from 'as-proto/assembly';
import { BlockInput } from './block-input';
import { NoFromTxInput } from './no-from-tx-input';

export class TxVerifyInput {
  static encode(message: TxVerifyInput, writer: Writer): void {
    const tx = message.tx;
    if (tx !== null) {
      writer.uint32(10);
      writer.fork();
      NoFromTxInput.encode(tx, writer);
      writer.ldelim();
    }

    const block = message.block;
    if (block !== null) {
      writer.uint32(18);
      writer.fork();
      BlockInput.encode(block, writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.bytes(message.validationData);

    writer.uint32(34);
    writer.bytes(message.callData);
  }

  static decode(reader: Reader, length: i32): TxVerifyInput {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TxVerifyInput();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tx = NoFromTxInput.decode(reader, reader.uint32());
          break;

        case 2:
          message.block = BlockInput.decode(reader, reader.uint32());
          break;

        case 3:
          message.validationData = reader.bytes();
          break;

        case 4:
          message.callData = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tx: NoFromTxInput | null;
  block: BlockInput | null;
  validationData: Uint8Array;
  callData: Uint8Array;

  constructor(
    tx: NoFromTxInput | null = null,
    block: BlockInput | null = null,
    validationData: Uint8Array = new Uint8Array(0),
    callData: Uint8Array = new Uint8Array(0),
  ) {
    this.tx = tx;
    this.block = block;
    this.validationData = validationData;
    this.callData = callData;
  }
}

export function encodeTxVerifyInput(message: TxVerifyInput): Uint8Array {
  return Protobuf.encode(message, TxVerifyInput.encode);
}

export function decodeTxVerifyInput(buffer: Uint8Array): TxVerifyInput {
  return Protobuf.decode<TxVerifyInput>(buffer, TxVerifyInput.decode);
}
