// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader } from 'as-proto/assembly';

export class ValidatorParams {
  static encode(message: ValidatorParams, writer: Writer): void {
    const pubKeyTypes = message.pubKeyTypes;
    if (pubKeyTypes.length !== 0) {
      for (let i: i32 = 0; i < pubKeyTypes.length; ++i) {
        writer.uint32(10);
        writer.string(pubKeyTypes[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): ValidatorParams {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ValidatorParams();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.pubKeyTypes.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  pubKeyTypes: Array<string>;

  constructor(pubKeyTypes: Array<string> = []) {
    this.pubKeyTypes = pubKeyTypes;
  }
}
